site_name: Tiny-listener
site_description: A lightweight event framework.
repo_name: molto0504/tiny-listener
repo_url: https://github.com/molto0504/tiny-listener
edit_uri: ""
site_author: molto

theme:
  name: "material"
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"

nav:
  - Introduction: "index.md"
  - HTTP listener: "http-listener.md"
  - MQTT listener: "mqtt-listener.md"
  - TCP listener: "tcp-listener.md"


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      css_class: highlight
  - toc:
      permalink: true